### ISSUE TITLE
[Idea] Merge your project with MCC!

### ISSUE THREAD

**Issue by Panossa** [AjaxGb/Sublime-MCFunction#2]
Hello there! I'd like to ask whether you could/would like to merge your project with the MCC syntax highlighter found here: https://github.com/42iscool42/MCC#minecraft-command-code-syntax-highlighter
It would be REALLY cool if we would have ONE syntax/language file which automatically applies to either .mcc or .mcfunction files. Basically the same syntax highlighting as in MCC but with # being a comment and also standard support for mcc and mcfunction files.

~Panossa

**Comment by AjaxGb** [comment]
I think that MCC and MCFunction have different design philosophies.

MCC tries to know about every valid option, and highlights everything else as an error. For example, using NBT tag names that MCC does not recognize will display an error, even in cases where that is perfectly valid (such as in item `tag:{}`s). Namespaces other than `minecraft:` also display an error, and commands it does not recognize will not be highlighted.

MCFunction, on the other hand, is less discriminating. Wherever possible, I have tried to only include general rules about what valid options look like, rather than list them all by hand. While this does mean that MCFunction is less likely to warn the user about mistakes, it is also less eager to correct them in cases where it might be wrong, and it will hopefully age more gracefully should I get behind in updates.

I believe that both approaches have their merits. I prefer mine, and presumably the creators of MCC prefer theirs. I am not going to close my project for the sake of uniformity. MCC is of course free to add # comments and `.mcfunction` detection, which should take them about five minutes.
