### ISSUE TITLE
Syntax highlighting issues with execute command

### ISSUE THREAD

**Issue by Alluysl** [AjaxGb/Sublime-MCFunction#6]
![image](https://user-images.githubusercontent.com/48528607/127527662-65e3d906-1545-46ef-be9c-c892f5c4c9d7.png)
becomes
![image](https://user-images.githubusercontent.com/48528607/127527605-2ffdd20b-d145-4d0a-a68b-e1ee8692667b.png)

Other similar issue:
![image](https://user-images.githubusercontent.com/48528607/127527933-eac311e9-f1b1-4d32-8492-9a2c5fb5fe12.png)

**Comment by AjaxGb** [comment]
Yep, as mentioned in the README, this package has been discontinued since 1.13 released. Any 1.13 syntax it manages to highlight is mostly by accident. I strongly recommend the actively maintained [language-mcfunction](https://github.com/Arcensoth/language-mcfunction#installing-the-sublimetext-package) package by Arcensoth instead.
